"use client";

// ─────────────────────────────────────────────────────────────────────────────
// ExplanationPanel — AI narrative over deterministic figures.
//
// The numbers elsewhere are computed truth (mono). This panel is COMMENTARY: it
// is deliberately visually distinct — a labeled, tinted panel, prose in the body
// sans (never mono), with a standing disclaimer that the words are AI-generated
// while the figures are computed. If the service is down it degrades to a quiet
// note; the numbers it would describe are always already on screen.
// ─────────────────────────────────────────────────────────────────────────────

import { useEffect, useRef, useState } from "react";
import { Sparkles } from "lucide-react";

import { useKerfStore } from "@/lib/store";

type Status = "idle" | "loading" | "done" | "error";

export function ExplanationPanel({
  kind,
  depth = "deep",
  getPayload,
  idleLabel,
  contextKey,
}: {
  kind: "cascade" | "concentration";
  depth?: "fast" | "deep";
  getPayload: () => Record<string, unknown>;
  idleLabel: string;
  /** ties the saved narrative to the exact state it described. Callers should
   *  ALSO pass this as the React `key` so the panel resets instantly when the
   *  scenario changes — a stale narrative must never sit under fresh numbers. */
  contextKey?: string;
}) {
  const [status, setStatus] = useState<Status>("idle");
  const [explanation, setExplanation] = useState("");
  const controllerRef = useRef<AbortController | null>(null);

  // abort any in-flight request if this panel unmounts (e.g. scenario change
  // remounts it via key) — the late response can never paint over fresh data.
  useEffect(() => () => controllerRef.current?.abort(), []);

  async function run() {
    controllerRef.current?.abort();
    const controller = new AbortController();
    controllerRef.current = controller;
    // the exact state this request describes — defense beyond abort
    const firedFor = contextKey;
    setStatus("loading");
    try {
      const res = await fetch("/api/explain", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ kind, depth, payload: { kind, ...getPayload() } }),
        signal: controller.signal,
      });
      const data = await res.json();
      // drop if aborted or the world moved on while we waited
      if (controller.signal.aborted || firedFor !== contextKey) return;
      if (!res.ok || !data.explanation) {
        setStatus("error");
        return;
      }
      setExplanation(data.explanation);
      setStatus("done");
      // persist so it can travel into the risk brief — keyed to this exact state
      if (contextKey) {
        useKerfStore.getState().setExplanation({
          contextKey,
          kind,
          text: data.explanation,
          tier: data.tier ?? "",
        });
      }
    } catch (err) {
      if (controller.signal.aborted) return; // expected on scenario change
      if (err instanceof DOMException && err.name === "AbortError") return;
      setStatus("error");
    }
  }

  if (status === "idle") {
    return (
      <button
        onClick={run}
        className="inline-flex items-center gap-2 rounded-md border border-line px-3 py-2 font-mono text-xs text-ink/70 transition-colors hover:border-green hover:text-ink"
      >
        <Sparkles className="size-3.5 text-green" strokeWidth={1.75} />
        {idleLabel}
      </button>
    );
  }

  if (status === "loading") {
    return (
      <div className="inline-flex items-center gap-2 font-mono text-xs text-ink/50">
        <Sparkles className="size-3.5 animate-pulse text-green" strokeWidth={1.75} />
        generating explanation…
      </div>
    );
  }

  if (status === "error") {
    return (
      <div className="rounded-md border border-dashed border-line px-3 py-2 font-mono text-xs text-ink/45">
        explanation unavailable right now — the figures above stand on their own.{" "}
        <button onClick={run} className="text-green underline-offset-2 hover:underline">
          retry
        </button>
      </div>
    );
  }

  // done — the distinct commentary panel
  return (
    <div className="rounded-lg border border-green/30 bg-green/[0.04] p-4">
      <div className="mb-2 flex items-center gap-2">
        <Sparkles className="size-3.5 text-green" strokeWidth={1.75} />
        <span className="font-sans text-xs lowercase tracking-[0.15em] text-green">
          ai explanation
        </span>
      </div>
      {/* prose in SANS — never mono — so it never reads as a computed figure */}
      <p className="font-sans text-sm leading-relaxed text-ink/85">{explanation}</p>
      <p className="mt-3 border-t border-green/15 pt-2 font-mono text-[11px] leading-snug text-ink/45">
        narrative generated by AI from the figures above — the numbers are computed
        deterministically; the words are not.{" "}
        <button onClick={run} className="text-green underline-offset-2 hover:underline">
          re-explain
        </button>
      </p>
    </div>
  );
}
